// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// GetUserIDByUUID provides a mock function with given fields: ctx, uuid
func (_m *UserRepository) GetUserIDByUUID(ctx context.Context, uuid string) (uint64, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetUserIDByUUID")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (uint64, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) uint64); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreOTP provides a mock function with given fields: ctx, userID, otp, requestID
func (_m *UserRepository) StoreOTP(ctx context.Context, userID uint64, otp string, requestID string) error {
	ret := _m.Called(ctx, userID, otp, requestID)

	if len(ret) == 0 {
		panic("no return value specified for StoreOTP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, string, string) error); ok {
		r0 = rf(ctx, userID, otp, requestID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateOTPStatus provides a mock function with given fields: ctx, userID, otp, requestID
func (_m *UserRepository) UpdateOTPStatus(ctx context.Context, userID uint64, otp string, requestID string) error {
	ret := _m.Called(ctx, userID, otp, requestID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOTPStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, string, string) error); ok {
		r0 = rf(ctx, userID, otp, requestID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
