// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// GenerateOTP provides a mock function with given fields: ctx, userUUID, requestID
func (_m *UserService) GenerateOTP(ctx context.Context, userUUID string, requestID string) (string, error) {
	ret := _m.Called(ctx, userUUID, requestID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateOTP")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, userUUID, requestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, userUUID, requestID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userUUID, requestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateOTP provides a mock function with given fields: ctx, userID, otp, requestID
func (_m *UserService) ValidateOTP(ctx context.Context, userID string, otp string, requestID string) error {
	ret := _m.Called(ctx, userID, otp, requestID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateOTP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, userID, otp, requestID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
